/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillasRouteImport } from './routes/villas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocationRouteImport } from './routes/location'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EstateRouteImport } from './routes/estate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicInquiryRouteImport } from './routes/api/public/inquiry'

const VillasRoute = VillasRouteImport.update({
  id: '/villas',
  path: '/villas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EstateRoute = EstateRouteImport.update({
  id: '/estate',
  path: '/estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInquiryRoute = ApiPublicInquiryRouteImport.update({
  id: '/api/public/inquiry',
  path: '/api/public/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/estate': typeof EstateRoute
  '/gallery': typeof GalleryRoute
  '/investment': typeof InvestmentRoute
  '/location': typeof LocationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/villas': typeof VillasRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/estate': typeof EstateRoute
  '/gallery': typeof GalleryRoute
  '/investment': typeof InvestmentRoute
  '/location': typeof LocationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/villas': typeof VillasRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/estate': typeof EstateRoute
  '/gallery': typeof GalleryRoute
  '/investment': typeof InvestmentRoute
  '/location': typeof LocationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/villas': typeof VillasRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/amenities'
    | '/blogs'
    | '/contact'
    | '/estate'
    | '/gallery'
    | '/investment'
    | '/location'
    | '/sitemap.xml'
    | '/villas'
    | '/api/public/inquiry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/amenities'
    | '/blogs'
    | '/contact'
    | '/estate'
    | '/gallery'
    | '/investment'
    | '/location'
    | '/sitemap.xml'
    | '/villas'
    | '/api/public/inquiry'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/amenities'
    | '/blogs'
    | '/contact'
    | '/estate'
    | '/gallery'
    | '/investment'
    | '/location'
    | '/sitemap.xml'
    | '/villas'
    | '/api/public/inquiry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AmenitiesRoute: typeof AmenitiesRoute
  BlogsRoute: typeof BlogsRoute
  ContactRoute: typeof ContactRoute
  EstateRoute: typeof EstateRoute
  GalleryRoute: typeof GalleryRoute
  InvestmentRoute: typeof InvestmentRoute
  LocationRoute: typeof LocationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VillasRoute: typeof VillasRoute
  ApiPublicInquiryRoute: typeof ApiPublicInquiryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villas': {
      id: '/villas'
      path: '/villas'
      fullPath: '/villas'
      preLoaderRoute: typeof VillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estate': {
      id: '/estate'
      path: '/estate'
      fullPath: '/estate'
      preLoaderRoute: typeof EstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inquiry': {
      id: '/api/public/inquiry'
      path: '/api/public/inquiry'
      fullPath: '/api/public/inquiry'
      preLoaderRoute: typeof ApiPublicInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AmenitiesRoute: AmenitiesRoute,
  BlogsRoute: BlogsRoute,
  ContactRoute: ContactRoute,
  EstateRoute: EstateRoute,
  GalleryRoute: GalleryRoute,
  InvestmentRoute: InvestmentRoute,
  LocationRoute: LocationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VillasRoute: VillasRoute,
  ApiPublicInquiryRoute: ApiPublicInquiryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
